name: BlockBan
version: 1.0.0
main: io.papermc.blockBan.BlockBan
description: An example plugin
author: PaperMC
website: https://papermc.io
api-version: '1.21'
depend: [WorldGuard, LuckPerms]
commands:
  blockban:
    description:
    usage: /<command> <text> 
    permission: BlockBan.Admin
